[mgr]
sort_dir_first = true
show_hidden = true

[opener]
open_pdf = [
  { run = "papers %s", orphan = true, for = "unix"},
]
open_image = [
  { run = "loupe %s", orphan = true, for = "unix" },
]

office = [
  { run = "onlyoffice-desktopeditors %s", orphan = true},
]

[open]
prepend_rules = [
  { url = "*.pdf", use = "open_pdf" },
  { url = "*.png", use = "open_image" },
  { url = "*.jpg", use = "open_image" },
  { url = "*.docx", use = "office" },
  { url  = "*.doc",  use = "office" },
  { url = "*.xlsx", use = "office" },
  { url = "*.xls",  use = "office" },
  { url = "*.pptx", use = "office" },
  { url = "*.ppt",  use = "office" }
]
