general {
    lock_cmd = pidof hyprlock || hyprlock
}

# Listener para apagar la pantalla después de 5.5 minutos
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Listener para suspender el sistema después de 30 minutos (no más de una vez)
listener {
    timeout = 1800
    on-timeout = systemctl suspend --no-block
    never = systemctl resume --no-block
}