cursor            #e1b7f5
cursor_text_color #432255

foreground            #e9e0e7
background            #110d12
selection_foreground  #382c3e
selection_background  #d3c0d8
url_color             #d3c0d8

#: black 000000 767676
color0  #161217
color8  #383339
#: red cc0403 f2201f
color1  #0e8375
color9  #40ead6
#: green 19cb00 23fd00
color2  #d3c0d8
color10 #f0dcf4
#: yellow cecb00 fffd00
color3  #f4b7b7
color11 #ffdad9
#: blue 0d73cc 1a8fff
color4  #ffffff
color12 #ffffff
#: magenta cb1ed1 fd28ff
color5  #504255
color13 #d3c0d8
#: cyan 0dcdcd 14ffff
color6  #663b3b
color14 #f4b7b7
#: white dddddd ffffff
color7  #cec3ce
color15 #e9e0e7

mark1_foreground #2c0b3e
mark1_background #f5d9ff
mark2_foreground #231728
mark2_background #f0dcf4
mark3_foreground #331112
mark3_background #ffdad9

active_tab_foreground #432255
active_tab_background #e1b7f5
inactive_tab_foreground #f5d9ff
inactive_tab_background #5b396d

active_border_color #e1b7f5
inactive_border_color #432255
# bell_border_color #ff5a00
