cursor            #90d5ae
cursor_text_color #003823

foreground            #dee4de
background            #0a0f0c
selection_foreground  #203529
selection_background  #b4ccbc
url_color             #b4ccbc

#: black 000000 767676
color0  #0f1511
color8  #303632
#: red cc0403 f2201f
color1  #48584d
color9  #93a699
#: green 19cb00 23fd00
color2  #b4ccbc
color10 #d0e8d7
#: yellow cecb00 fffd00
color3  #a4cddd
color11 #c0e9fa
#: blue 0d73cc 1a8fff
color4  #ffffff
color12 #ffffff
#: magenta cb1ed1 fd28ff
color5  #364b3f
color13 #b4ccbc
#: cyan 0dcdcd 14ffff
color6  #234c59
color14 #a4cddd
#: white dddddd ffffff
color7  #c0c9c1
color15 #dee4de

mark1_foreground #002112
mark1_background #abf2c9
mark2_foreground #0b1f15
mark2_background #d0e8d7
mark3_foreground #001f28
mark3_background #c0e9fa

active_tab_foreground #003823
active_tab_background #90d5ae
inactive_tab_foreground #abf2c9
inactive_tab_background #005234

active_border_color #90d5ae
inactive_border_color #003823
# bell_border_color #ff5a00
