# --- Main Colors ---
background            #0f1511
foreground            #dee4de
cursor                #dee4de
cursor_text_color     #0f1511

selection_background  #364b3f
selection_foreground  #d0e8d7

url_color             #a4cddd

# --- ANSI Colors ---
color0                #0f1511
color1                #ffb4ab
color2                #a4cddd
color3                #b4ccbc
color4                #90d5ae
color5                #a4cddd
color6                #b4ccbc
color7                #dee4de

color8                #404943
color9                #93000a
color10               #234c59
color11               #364b3f
color12               #005234
color13               #364b3f
color14               #234c59
color15               #c0c9c1

# --- Starship Prompt Bubbles ---
color255              #005234
color254              #90d5ae
color253              #364b3f
color252              #b4ccbc
color251              #234c59
color250              #a4cddd
color249              #93000a
color248              #ffb4ab

color232              #abf2c9
color233              #003823
color234              #d0e8d7
color235              #203529
color236              #c0e9fa
color237              #053542
color238              #ffdad6
color239              #690005
color240              #abf2c9

# Matched with unthemed light/dark
color243              #90d5ae
color244              #ffb4ab
color245              #404943

# --- UI Elements ---
active_tab_foreground   #003823
active_tab_background   #90d5ae
inactive_tab_foreground #abf2c9
inactive_tab_background #005234

active_border_color     #90d5ae
inactive_border_color   #8a938c

# --- Marks ---
mark1_foreground        #002112
mark1_background        #abf2c9
mark2_foreground        #0b1f15
mark2_background        #d0e8d7
mark3_foreground        #001f28
mark3_background        #c0e9fa
