# --- Main Colors ---
background            #231917
foreground            #f1dfdb
cursor                #f1dfdb
cursor_text_color     #1a110f

selection_background  #5d3f38
selection_foreground  #ffdad2

url_color             #dac58c

# --- ANSI Colors ---
color0                #1a110f
color1                #ffb4ab
color2                #dac58c
color3                #e7bdb3
color4                #ffb4a3
color5                #dac58c
color6                #e7bdb3
color7                #f1dfdb

color8                #534340
color9                #93000a
color10               #544519
color11               #5d3f38
color12               #723425
color13               #5d3f38
color14               #544519
color15               #d8c2bd

# --- Starship Prompt Bubbles ---
color255              #723425
color254              #ffb4a3
color253              #5d3f38
color252              #e7bdb3
color251              #544519
color250              #dac58c
color249              #93000a
color248              #ffb4ab

color232              #ffdad2
color233              #561f11
color234              #ffdad2
color235              #442a23
color236              #f7e1a6
color237              #3c2f04
color238              #ffdad6
color239              #690005
color240              #ffdad2

# Matched with unthemed light/dark
color243              #ffb4a3
color244              #ffb4ab
color245              #534340

# --- UI Elements ---
active_tab_foreground   #561f11
active_tab_background   #ffb4a3
inactive_tab_foreground #ffdad2
inactive_tab_background #723425

active_border_color     #ffb4a3
inactive_border_color   #a08c88

# --- Marks ---
mark1_foreground        #3a0a02
mark1_background        #ffdad2
mark2_foreground        #2c1510
mark2_background        #ffdad2
mark3_foreground        #241a00
mark3_background        #f7e1a6
