cursor            #97d5a4
cursor_text_color #00391a

foreground            #dfe4dc
background            #0b0f0b
selection_foreground  #223526
selection_background  #b7ccb8
url_color             #b7ccb8

#: black 000000 767676
color0  #101510
color8  #313631
#: red cc0403 f2201f
color1  #4ae26f
color9  #cef7d8
#: green 19cb00 23fd00
color2  #b7ccb8
color10 #d2e8d3
#: yellow cecb00 fffd00
color3  #a2ced9
color11 #beeaf5
#: blue 0d73cc 1a8fff
color4  #15512c
color12 #97d5a4
#: magenta cb1ed1 fd28ff
color5  #384b3c
color13 #b7ccb8
#: cyan 0dcdcd 14ffff
color6  #204d56
color14 #a2ced9
#: white dddddd ffffff
color7  #c1c9bf
color15 #dfe4dc

mark1_foreground #00210d
mark1_background #b3f1bf
mark2_foreground #0d1f12
mark2_background #d2e8d3
mark3_foreground #001f25
mark3_background #beeaf5

active_tab_foreground #00391a
active_tab_background #97d5a4
inactive_tab_foreground #b3f1bf
inactive_tab_background #15512c

active_border_color #97d5a4
inactive_border_color #00391a
# bell_border_color #ff5a00
