# Font configuration
font_family      JetBrainsMono Nerd Font Mono
font_size        10.0

# Theme and colors
# include          themes/tokyonight.conf
include          themes/matugen.conf

# Window appearance
window_padding_width    20
window_padding_height   5
hide_window_decorations titlebar-only
# macos_titlebar_color    dark
scrollbar_handle_opacity 0
scrollbar_track_opacity  0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0
sync_to_monitor no

# Background opacity and blur
background_opacity      0.80
background_blur         20

# Clipboard settings
copy_on_select          yes
strip_trailing_spaces   smart

# Shell integration
shell_integration       enabled

# Terminal settings
term                    xterm-256color

# Clear any default Alt+Q binding to allow @ symbol (Spanish keyboard)
# Remove any existing binding for these keys
map opt+q               
map alt+q               

# Performance optimizations
repaint_delay           10
input_delay             3
sync_to_monitor         yes

# Scrollback
scrollback_lines        2000
scrollback_pager bash -c "ansifilter > /tmp/kitty_scroll.txt && nvim /tmp/kitty_scroll.txt -c 'normal G'"

# Tab configuration
tab_bar_style           powerline
tab_powerline_style     slanted


# BEGIN_KITTY_THEME
# Matugen
include current-theme.conf
# END_KITTY_THEME
