[ids]
*

[main]
# Convierte CapsLock en una tecla dual:
# Si se presiona sola = Escape (ideal para Vim)
# Si se mantiene presionada = Activa la capa "nav"
capslock = overload(nav, esc)

[nav]
# Definimos los binds de Vim para las flechas
h = left
j = down
k = up
l = right

# Extras útiles para completar el combo de navegación:
u = pageup
d = pagedown
0 = home
$ = end
