# --- CONFIGURACIÓN PARA CUALQUIER OTRO TECLADO ---
[ids]
*

[main]
# En los demás teclados, el CapsLock funciona igual, 
# pero no intercambiamos Meta/Alt.
capslock = overload(nav, esc)

# --- CAPA DE NAVEGACIÓN (Compartida para todos) ---
[nav]
h = left
j = down
k = up
l = right
u = pageup
d = pagedown
0 = home
$ = end
