# Directorios Base XDG
XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"
XDG_STATE_HOME="$HOME/.local/state"

# Redirecciones a XDG (Dev Tools & Configs)
CARGO_HOME="$XDG_DATA_HOME/cargo"
RUSTUP_HOME="$XDG_DATA_HOME/rustup"
BUN_INSTALL="$XDG_DATA_HOME/bun"
NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"

ZDOTDIR="$XDG_CONFIG_HOME/zsh"
ZSH="$XDG_DATA_HOME/oh-my-zsh"
HISTFILE="$XDG_DATA_HOME/zsh/history"
HISTSIZE=10000
SAVEHIST=10000

CLAUDE_CONFIG_DIR="$XDG_CONFIG_HOME/claude"
TMUX_CONF="$XDG_CONFIG_HOME/tmux/tmux.conf"
GNUPGHOME="$XDG_DATA_HOME/gnupg"
WGETRC="$XDG_CONFIG_HOME/wgetrc"

KEYD_CONF="/etc/keyd/default.conf"
SDDM_CONF="/usr/lib/sddm/sddm.conf.d/default.conf"
APPS_DIR="$XDG_DATA_HOME/applications/"

NOTES_DIR="$HOME/documents/notas"
