cursor            #ffb779
cursor_text_color #4c2700

foreground            #efe0d6
background            #140d08
selection_foreground  #412c19
selection_background  #e3c0a5
url_color             #e3c0a5

#: black 000000 767676
color0  #19120c
color8  #3c332c
#: red cc0403 f2201f
color1  #5e5169
color9  #aa9fb4
#: green 19cb00 23fd00
color2  #e3c0a5
color10 #ffdcc1
#: yellow cecb00 fffd00
color3  #c3cb97
color11 #dfe7b1
#: blue 0d73cc 1a8fff
color4  #6b3b04
color12 #ffb779
#: magenta cb1ed1 fd28ff
color5  #5a422e
color13 #e3c0a5
#: cyan 0dcdcd 14ffff
color6  #434a22
color14 #c3cb97
#: white dddddd ffffff
color7  #d6c3b6
color15 #efe0d6

mark1_foreground #2e1500
mark1_background #ffdcc1
mark2_foreground #2a1707
mark2_background #ffdcc1
mark3_foreground #181e00
mark3_background #dfe7b1

active_tab_foreground #4c2700
active_tab_background #ffb779
inactive_tab_foreground #ffdcc1
inactive_tab_background #6b3b04

active_border_color #ffb779
inactive_border_color #4c2700
# bell_border_color #ff5a00
