cursor            #8dd5b3
cursor_text_color #003826

foreground            #dee4de
background            #0a0f0c
selection_foreground  #1f352b
selection_background  #b3ccbe
url_color             #b3ccbe

#: black 000000 767676
color0  #0f1512
color8  #303632
#: red cc0403 f2201f
color1  #b68c20
color9  #eace85
#: green 19cb00 23fd00
color2  #b3ccbe
color10 #cfe9d9
#: yellow cecb00 fffd00
color3  #a5ccdf
color11 #c1e8fc
#: blue 0d73cc 1a8fff
color4  #005139
color12 #8dd5b3
#: magenta cb1ed1 fd28ff
color5  #354b40
color13 #b3ccbe
#: cyan 0dcdcd 14ffff
color6  #244b5b
color14 #a5ccdf
#: white dddddd ffffff
color7  #bfc9c2
color15 #dee4de

mark1_foreground #002115
mark1_background #a8f2ce
mark2_foreground #092016
mark2_background #cfe9d9
mark3_foreground #001f29
mark3_background #c1e8fc

active_tab_foreground #003826
active_tab_background #8dd5b3
inactive_tab_foreground #a8f2ce
inactive_tab_background #005139

active_border_color #8dd5b3
inactive_border_color #003826
# bell_border_color #ff5a00
