cursor            #c9bfff
cursor_text_color #31285f

foreground            #e5e1e9
background            #0e0d13
selection_foreground  #312e41
selection_background  #c9c3dc
url_color             #c9c3dc

#: black 000000 767676
color0  #141318
color8  #36343a
#: red cc0403 f2201f
color1  #4c414d
color9  #9b8a9d
#: green 19cb00 23fd00
color2  #c9c3dc
color10 #e5dff9
#: yellow cecb00 fffd00
color3  #edb8cd
color11 #ffd8e6
#: blue 0d73cc 1a8fff
color4  #473f77
color12 #c9bfff
#: magenta cb1ed1 fd28ff
color5  #484459
color13 #c9c3dc
#: cyan 0dcdcd 14ffff
color6  #623b4c
color14 #edb8cd
#: white dddddd ffffff
color7  #c9c5d0
color15 #e5e1e9

mark1_foreground #1b1149
mark1_background #e5deff
mark2_foreground #1c192b
mark2_background #e5dff9
mark3_foreground #301120
mark3_background #ffd8e6

active_tab_foreground #31285f
active_tab_background #c9bfff
inactive_tab_foreground #e5deff
inactive_tab_background #473f77

active_border_color #c9bfff
inactive_border_color #31285f
# bell_border_color #ff5a00
