# : Manager [[[

[mgr]
cwd = { fg = "#efe0d6" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#bfcf63", bg = "#bfcf63" }
marker_cut      = { fg = "#dfe7b1", bg = "#dfe7b1" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#c3cb97", bg = "#c3cb97" }

# Count
count_copied   = { fg = "#181e00", bg = "#dfe7b1" }
count_cut      = { fg = "#181e00", bg = "#dfe7b1" }
count_selected = { fg = "#4c2700", bg = "#c3cb97" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb779" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb779", bold = true, bg = "#19120c" }
inactive  = { fg = "#e3c0a5", bg = "#19120c" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb779", fg = "#4c2700", bold = true }
normal_alt  = { bg = "#51443b", fg = "#d6c3b6" }

# Select mode
select_main = { bg = "#e3c0a5", fg = "#412c19", bold = true }
select_alt  = { bg = "#51443b", fg = "#d6c3b6" }

# Unset mode
unset_main = { bg = "#c3cb97", fg = "#2d330e", bold = true }
unset_alt  = { bg = "#51443b", fg = "#d6c3b6" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#b66f39" }
perm_write = { fg = "#7c8643" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#afc33c" }
perm_sep   = { fg = "#ff8628" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb779", bg = "#413731" }
progress_error  = { fg = "#ffb4ab", bg = "#413731" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413731" }
cand = { fg = "#ffb779" }
rest = { fg = "#4c2700" }
desc = { fg = "#efe0d6" }
separator = " ▶ "
separator_style = { fg = "#efe0d6" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#c3cb97" }
title_warn  = { fg = "#ffb779" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb779" }
active = { fg = "#c3cb97", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb779" }
value  = { fg = "#efe0d6" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb779", bg = "#4c2700" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb779" }
title   = {}
hovered = { fg = "#dfe7b1", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#efe0d6" }
run    = { fg = "#efe0d6" }
footer = { fg = "#412c19", bg = "#e3c0a5" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#efe0d6" },
    { url = "*/", fg = "#ffb779" },
]

# : ]]]
