# : Manager [[[

[mgr]
cwd = { fg = "#f0dedf" }

# Find
find_keyword  = { fg = "#ffb4ab", bold = true, italic = true, underline = true }
find_position = { fg = "#ffb4ab", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#ffae4f", bg = "#ffae4f" }
marker_cut      = { fg = "#ffddb5", bg = "#ffddb5" }
marker_marked   = { fg = "#ffb4ab", bg = "#ffb4ab" }
marker_selected = { fg = "#e8c08e", bg = "#e8c08e" }

# Count
count_copied   = { fg = "#2a1800", bg = "#ffddb5" }
count_cut      = { fg = "#2a1800", bg = "#ffddb5" }
count_selected = { fg = "#561d25", bg = "#e8c08e" }

# Border
border_symbol = "│"
border_style  = { fg = "#ffb2b8" }

# : ]]]


# : Indicator [[[

[indicator]
padding = { open = "█", close = "█" }

# : ]]]


# : Tabs [[[

[tabs]
active    = { fg = "#ffb2b8", bold = true, bg = "#1a1112" }
inactive  = { fg = "#e5bdbf", bg = "#1a1112" }
sep_inner = { open = "[", close = "]" }

# : ]]]


# : Mode [[[

[mode]
# Mode
normal_main = { bg = "#ffb2b8", fg = "#561d25", bold = true }
normal_alt  = { bg = "#524344", fg = "#d7c1c2" }

# Select mode
select_main = { bg = "#e5bdbf", fg = "#44292b", bold = true }
select_alt  = { bg = "#524344", fg = "#d7c1c2" }

# Unset mode
unset_main = { bg = "#e8c08e", fg = "#442b06", bold = true }
unset_alt  = { bg = "#524344", fg = "#d7c1c2" }

# : ]]]


# : Status [[[

[status]
sep_left  = { open = "🭁", close = "🭠" }
sep_right = { open = "🭁", close = "🭠" }

# Permissions
perm_type  = { fg = "#ba4f55" }
perm_write = { fg = "#b87725" }
perm_read  = { fg = "#ff2b12" }
perm_exec  = { fg = "#ff971c" }
perm_sep   = { fg = "#ff4146" }

# Progress
progress_label  = { bold = true }
progress_normal = { fg = "#ffb2b8", bg = "#413737" }
progress_error  = { fg = "#ffb4ab", bg = "#413737" }

# : ]]]


# : Which [[[

[which]
cols = 3
mask = { bg = "#413737" }
cand = { fg = "#ffb2b8" }
rest = { fg = "#561d25" }
desc = { fg = "#f0dedf" }
separator = " ▶ "
separator_style = { fg = "#f0dedf" }

# : ]]]


# : Notify [[[

[notify]
title_info  = { fg = "#e8c08e" }
title_warn  = { fg = "#ffb2b8" }
title_error = { fg = "#ffb4ab" }

# : ]]]


# : Picker [[[

[pick]
border = { fg = "#ffb2b8" }
active = { fg = "#e8c08e", bold = true }
inactive = {}

# : ]]]


# : Input [[[

[input]
border = { fg = "#ffb2b8" }
value  = { fg = "#f0dedf" }

# : ]]]


# : Completion [[[

[cmp]
border = { fg = "#ffb2b8", bg = "#561d25" }

# : ]]]


# : Tasks [[[

[tasks]
border  = { fg = "#ffb2b8" }
title   = {}
hovered = { fg = "#ffddb5", underline = true }

# : ]]]


# : Help [[[

[help]
on     = { fg = "#f0dedf" }
run    = { fg = "#f0dedf" }
footer = { fg = "#44292b", bg = "#e5bdbf" }

# : ]]]


# : File-specific styles [[[

[filetype]

rules = [
    # Images
    { mime = "image/*", fg = "#94e2d5" },

    # Media
    { mime = "{audio,video}/*", fg = "#f9e2af" },

    # Archives
    { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "#f5c2e7" },

    # Documents
    { mime = "application/{pdf,doc,rtf}", fg = "#a6e3a1" },

    # Special files
    { name = "*", is = "orphan", bg = "#93000a" },
    { name = "*", is = "exec", fg = "#ffdad6" },

    # Fallback
    { url = "*", fg = "#f0dedf" },
    { url = "*/", fg = "#ffb2b8" },
]

# : ]]]
