[general]
import = [ "colors.toml" ]
live_config_reload = true

[font]
size = 12
normal = { family = "Maple Mono NF", style = "Regular"}
bold = { family = "Maple Mono NF SemiBold", style = "SemiBold" }
italic = { family = "Maple Mono NF", style = "Italic" }
bold_italic = { family = "Maple Mono NF", style = "Bold Italic" }

[cursor]
vi_mode_style = { shape = "Block", blinking = "On" }

[window]
padding = { x = 20, y = 20}

[keyboard]
bindings = [
  {
    # En Vi_mode presionar "a" para salir
    key = "A",
    mode = "Vi|~Search",
    action = "ToggleViMode"
  },
  {
    # Arreglo para buscar con "/" en Vi_mode
    key = "/",
    mods = "Shift",
    mode = "Vi|~Search",
    action = "SearchForward"
  },
  {
    key = "+",
    mods = "Control",
    action = "IncreaseFontSize"
  },
  {
    key = "-",
    mods = "Control",
    action = "DecreaseFontSize"
  },
]
